Lab4WebProg/Lab4WebProg/urls.py
"""
Definition of urls for Lab4WebProg.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url('anketa/$', app.views.anketa, name='anketa'),
    url('blog/$', app.views.blog, name='blog'),
    url(r'^videopost$',app.views.videopost, name='videopost'),
    url(r'^newpost$',app.views.newpost, name='newpost'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^registration$', app.views.registration, name='registration'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Lab4WebProg/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment,Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))
class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title','description','content','image',) # требуется заполнить только поле text
        labels = {'title': "Заголовок",'description':"Краткое содержание", 'content': "Полное содержание",'image':"Картинка"} # метка к полю формы text

class AnketaForm(forms.Form):
    name = forms.CharField(label="Ваше имя", min_length=2, max_length=100)
    city = forms.CharField(label="Ваш город", min_length=2, max_length=100)
    job = forms.CharField(label="Ваш род занятий", min_length=2, max_length=100)
    gender = forms.ChoiceField(
        label="Ваш пол",
        choices=[("1", "Муж"), ("2", "Жен")],
        widget=forms.RadioSelect,
        initial=1,
    )
    internet = forms.ChoiceField(
        label="Вы путешествуете",
        choices=(
            ("1", "Раз в год"),
            ("2", "Два раза в год"),
            ("3", "Раз в два года"),
            ("4", "Никогда"),
        ),
        initial=1,
    )
    notice = forms.BooleanField(label="Получать новости на e-mail?", required=False)
    email = forms.EmailField(label="Ваш e-mail", min_length=7)
    message = forms.CharField(
        label="Что хотели бы посетить?", widget=forms.Textarea(attrs={"rows": 10, "cols": 30})
    )

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text

Lab4WebProg/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

Lab4WebProg/app/templates/app/anketa.html
{% extends "app/layout.html" %}
{% block content %}
{% if form != None %}
<h2>Просим Вас заполнить анкету.</h2><br>
<div>
    <form method="post">
        {%csrf_token%}
        <label for="{{ form.name.id_for_label}}">{{ form.name.label }}</label>
        {{form.name}} <br><br>
        <label for="{{ form.city.id_for_label}}">{{ form.city.label }}</label>
        {{form.city}} <br>
        <label for="{{ form.gender.id_for_label}}">{{ form.gender.label }}</label>
        {{form.gender}} 
        <label for="{{ form.job.id_for_label}}">{{ form.job.label }}</label><br>
        {{form.job}} <br><br>
        <label for="{{ form.internet.id_for_label}}">{{ form.internet.label }}</label><br>
        {{form.internet}} <br><br>
        <label for="{{ form.notice.id_for_label}}">{{ form.notice.label }}</label>
        {{form.notice}} <br><br>
        <label for="{{ form.email.id_for_label}}">{{ form.email.label }}</label>
        {{form.email}} <br><br>
        <label for="{{ form.message.id_for_label}}">{{ form.message.label }}</label><br>
        {{form.message}} <br><br>
        <input type="submit" value="Отправить" id = "b1">
    </form>
</div>
<h5>Отправьте, пожалуйста, заполненную анкету</h5>
{%else%}
<br><h2>Благодарим за предоставленную информацию!</h2>
<h3>Ваша анкета:</h3>
<ul>
    <li><span>Имя:</span>{{data.name}}</li>
    <li><span>Город:</span>{{data.city}}</li>
    <li><span>Пол:</span>{{data.gender}}</li>
    <li><span>Вид деятельности:</span>{{data.job}}</li>
    <li><span>Путешествуете:</span>{{data.internet}}</li>
    <li><span>Получать письмо сайта на e-mail:</span>{{data.notice}}</li>
    <li><span>Ваш e-mail:</span>{{data.email}}</li>
    <li><span>Хотелось бы посетить:</span>{{data.message}}</li>
</ul>
{% endif %}

<script>
    function Namefocus()
    {
     $('#id_name').css('background-color', 'LightCyan');
     $('#id_name').css('color', 'Blue');
    }
    function Nameblur()
    {
      $('#id_name').css('background-color', 'transparent');
      $('#id_name').css('color', 'Black');
    }
    function Emailfocus()
    {
    $('#id_email').css('background-color', 'Yellow');
    $('#id_email').css('color', 'Green');
    }
    function Emailblur()
    {
    $('#id_email').css('background-color', 'transparent');
    $('#id_email').css('color', 'Black');
    }
    function Cityfocus()
    {
    $('#id_city').css('background-color', 'Red');
    $('#id_city').css('color', 'Blue');
    }
    function Cityblur()
    {
    $('#id_city').css('background-color', 'transparent');
    $('#id_city').css('color', 'Black');
    }
    function Jobfocus()
    {
     $('#id_job').css('background-color', 'Black');
     $('#id_job').css('color', 'White');
    }
    function Jobblur()
    {
      $('#id_job').css('background-color', 'transparent');
      $('#id_job').css('color', 'Black');
    }
    function Buttonmouseover()
    {
    $('#b1').css('background-color', 'Green');
    $('#b1').css('color', 'Gray');
    }
    function Buttonmouseout()
    {
    $('#b1').css('background-color', 'transparent');
    $('#b1').css('color', 'Black');
    }
    $('#id_name').focus(Namefocus);
    $('#id_name').blur(Nameblur);
    $('#id_email').focus(Emailfocus);
    $('#id_email').blur(Emailblur);
    $('#id_city').focus(Cityfocus);
    $('#id_city').blur(Cityblur);
    $('#id_job').focus(Jobfocus);
    $('#id_job').blur(Jobblur);
    $('#b1').mouseover(Buttonmouseover);
    $('#b1').mouseout(Buttonmouseout);
</script>

{% endblock %}

Lab4WebProg/app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2> <br />

{% for post in posts %}

<hr/>

<div class="">

<h2> {{post.title}} </h2>

<h4> {{post.posted}} </h4>

<p> {{post.description}} </p>
<p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a></p>
</div>

{% endfor %}

{% endblock %}

Lab4WebProg/app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}
<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}

<img src="{{ post_1.image.url }}" alt=" Картинка статьи блога" width="200" height="100"/>

{% endif %}
{% autoescape off %}
<p> {{post_1.content|linebreaksbr}} </p>
{% endautoescape %}

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST" >{% csrf_token %} 
        <div>
            {{form.as_p}}
            <button type="submit" class="save btn btn-default" > Отправить </button>
        </div>
    </form>
{% else %}
<h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %}

{% for comment in comments %}
<hr/>
<h7> {{comment.date}} </h7>
<h5> {{comment.author}} </h5>
<p> {{comment.text|linebreaksbr}} </p>
{% endfor %}
<p><a href="{% url 'blog' %}">Назад</a></p>
{% endblock %}

Lab4WebProg/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Студентка 4-го курса СурГУ Третьякова А. А.<br />
    г. Сургут, ул. Энергетиков 22, корпус УНИКИТ<br />
    <abbr title="Телефон для связи">Телефон для связи:</abbr>
    +7(932)429-44-36
</address>

<address>
    <strong>Тех. поддержка:</strong> <a href="mailto:arinatretiakova27@gmail.com">arinatretiakova27@gmail.com</a>
</address>

{% endblock %}

Lab4WebProg/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Средневековые замки</h1>
    <p class="lead"> Первые укрепления в виде средневековых замков появились в IX - X вв. в то время, когда странам Центральной Европы ( Франции, Германии и Северной Италии) начала угрожать агрессия и вторжение варварских племён, и викингов. Это сильно мешало развитию империи, cозданной Карлом Великим. Для защиты земель начинали возводить укрепления из деревянных построек. Такая архитектура "прочного дерева" для более надёжной защиты добавлялась окружением землянного рва и вала. Через ров на цепочках или прочных верёвках опрокидывался навесной мост, по которому попадали в жилой посёлок. На гребне вала устанавливали частокол. Верхушка его ствола остро натачивалась орудиями труда и вкапывалась в землю на достаточно большой высоте, безопасной от проникновения вовнутрь укрепления. В XI веке замки стали строить на искусственных холмах. Такие холмы насыпали рядом с двором, ограждённым высоким частоколом.</p>
    <p><a href="http://srednyvek.ru/istoriya/zamok" class="btn btn-primary btn-large">Узнать больше &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Эдинбургский замок</h2>
        <p>
            Одна из самых известных достопримечательностей Шотландии — Эдинбургский замок, расположенный в самом центре города. Эта старинная прекрасная крепость на краю неприступного утеса долгое время была важным стратегическим объектом обороны страны. И до сих пор считается одной из штаб-квартир британской армии, хотя многие годы является архитектурной достопримечательностью, куда толпами ходят туристы.
        </p>
        <p><a class="btn btn-default" href="https://pytrip.ru/edinburgskij-zamok/">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Замок Керлаверок</h2>
        <p>Этот замок стал одним из самых первых замков Шотландии, сооружённых в камне. Он имел прямоугольную форму и был окружён рвом, через который имелся мост на северной стороне. На сегодняшний день от этой первой крепости, остались лишь следы фундамента. В 1270-ых племянник Джона, Герберт Максвелл, выстроил новый (существующий) замок, став его первым владельцем.</p>
        <p><a class="btn btn-default" href="https://worldartdalia.blogspot.com/2012/08/blog-post_7798.html">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Виндзорский замок</h2>
        <p>Сегодня Виндзорский замок известен на весь мир как летняя резиденция английских монархов, а в город ежедневно приезжают сотни и тысячи туристов, чтобы посмотреть на это чудо архитектуры и на хранящиеся в нем художественные ценности, услышать новые интересные факты его истории и подробности жизни королевы.</p>
        <p><a class="btn btn-default" href="https://www.miroworld.ru/vindzorskij-zamok/">Узнать больше&raquo;</a></p>
    </div>
</div>
{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">

    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>

        <li data-target="#myCarousel" data-slide-to="1"></li>

        <li data-target="#myCarousel" data-slide-to="2"></li>

        <li data-target="#myCarousel" data-slide-to="3"></li>

    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active">

            <img src="{% static 'app/content/banner1.svg' %} " alt="Первый слайд" class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Самые страшные замки мира

                    <a class="btn btn-default" href="https://patriotov.net/interesnoe/289-samye-strashnye-zamki-mira-dver-v-potustoronnyuyu-realnost">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src="{% static 'app/content/banner2.svg'%}" alt="Второй слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Самые красивые замки мира

                    <a class="btn btn-default" href="https://most-beauty.ru/mesta/samye-krasivye-zamki-mira.html">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src=" {% static 'app/content/banner3.svg'%} " alt="Третий слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Самые известные замки мира

                    <a class="btn btn-default" href="https://wikiway.com/dostoprimechatelnosti/zamki-kreposti/">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Предыдущий</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Следующий</span>

    </a>

</div>
{% endblock %}

Lab4WebProg/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - приложение Django</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
     <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/logo.jpg' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'videopost' %}"> Видео </a> </li>
                    <li><a href="{% url 'anketa' %}">Анкета</a></li>
                    {% if not user.is_authenticated %}
                     <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                    {% if user.is_superuser%}
                        <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

   
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

Lab4WebProg/app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}

{% load staticfiles %}

<a href ="https://wikiway.com/dostoprimechatelnosti/zamki-kreposti/" target="_blank"> <img src="{% static 'app/content/logo1.jpg' %}" alt="Logo 1"/></a></br>
<a href ="http://snovadoma.ru/castles/Castle/" target="_blank"> <img src="{% static 'app/content/logo2.jpg' %}" alt="Logo 2"/></a></br>
<a href ="https://allcastle.info/castle" target="_blank"> <img src="{% static 'app/content/logo3.jpg' %}" alt="Logo 3"/></a></br>
{% endblock %}

Lab4WebProg/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте локальную учетную запись для входа в систему.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильное имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

Lab4WebProg/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Приветствуем, {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Войти</a></li>
</ul>

{% endif %}

Lab4WebProg/app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data" >{% csrf_token %} 
    <div>
        {{blogform.as_p}}
        <button type="submit" class="save btn btn-default" > Сохранить статью </button>
    </div>
</form>
{% endblock %}

Lab4WebProg/app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Регистрация пользователя</h2>
<form method="POST" > {% csrf_token %}
<div>
{{ regform.as_p}}
<button type="submit" class="save btn btn-default" > Зарегистрироваться </button>
</div>
</form>
{% endblock %}

Lab4WebProg/app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}
<br>
<br>
<div>
    <h1>Замок Болдт:</h1>
    <video src="/media/video1.mp4" controls="controls" poster="/media/poster1.PNG" width="500" height="400"></video>
</div>
<hr>
<div>
    <h1>Замок Фантазия Форт:</h1>
    <video src="/media/video2.mp4" controls="controls" poster="/media/poster2.PNG" width="500" height="400"></video>
</div>
{% endblock %}